
name: checks

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  check:
    uses: chesskit-app/workflows/.github/workflows/check-swift-package.yaml@master
    secrets: inherit
    with:
       test_bundle: ChessKitEnginePackageTests
